condense_wildcard_suffixes = true
fn_params_layout = "Compressed"
format_code_in_doc_comments = true
format_macro_matchers = true
format_strings = true
hex_literal_case = "Upper"
imports_layout = "Vertical"
merge_derives = false
imports_granularity = "Crate"
newline_style = "Unix"
normalize_comments = true
reorder_impl_items = true
group_imports = "StdExternalCrate"
tab_spaces = 2
use_field_init_shorthand = true
version = "Two"
use_try_shorthand = true
wrap_comments = true
